### PR TITLE
poison 4.0

### PR DESCRIPTION
**Pull request by agramichael**

### CODE REVIEW

**Comment by zacksiri** [comment]
@aniruddhasd any chance we can merge this?

**Comment by aniruddhasd** [comment]
> @aniruddhasd any chance we can merge this?

Since it is a major version change in one of the dependencies<Poison 3 to 4>, wondering if I should bump up major for onesignal_elixir as well. What do you suggest? @zacksiri @agramichael

**Comment by zacksiri** [comment]
@aniruddhasd i think it's just a dependency change, there is no feature change in your library, also I do not believe changing from Poison 3.1 -> 4.0.1 has any concerning / breaking changes the user need to be aware of. 

I would say it can be a minor patch update.

you could just make it 0.2.0 and anyone who wishes to stay on poison 3.1 can stay with 0.1.5

**Review by aniruddhasd — CHANGES_REQUESTED** [review]
@agramichael Would appreciate if you could update this PR with a minor version change for the onesignal_elixir library in mix.exs 
Please update it to 0.2.0 from 0.1.7

**Comment by agramichael** [comment]
Done!

**Pull request merged**
